#!/bin/csh

set folder=/project/iapetus/coupled_core_cooling/DATA/2D
#set case1=CASE13
#set folder1=$folder/$case1/post
#set folder1=post
set disk="$2"
set CASE="$3"
set folder1="$CASE"/post

set nx=193
set nz=49

#set dx=0.9375 
#set dz=1.286458
#set dz=1.135
#set dx=0.1875
set dz=0.2
set dx=0.05 # x in degrees

set z0=0 # z in kilometers
#set z1=25
set z1=172
#set z1=212
set z2=252
#set x1=-90	
set x1=60
set x2=90

set xs=3
set zs=8

set zinc=8.5
set xinc=5

set frame1=$1 # timestep

mkdir -p "$disk"/temp_plots
set output="$folder1"/temp$frame1.ps
set output2="$disk"/temp_plots/`basename "$CASE"`\_step$frame1.pdf
set colort=t.cpt

if (-f "$colort") then
    /bin/rm "$colort"
endif
if (-f "$output") then
    /bin/rm "$output"
endif

#makecpt -Cwysiwyg -T75/110/5 -Z > $colort
gmt makecpt -Cwysiwyg -T75/275/40 -Z > "$colort"


set inputa="$folder1"/temp.$frame1
set inputb="$folder1"/tempdim.$frame1
set inputc="$folder1"/cmb.dat
awk '{print 90-$1, $2*'$z2', ($3*198+75)}' "$inputa" >! "$inputb"

gmt surface "$inputb" -Gmap.grd -R$x1/$x2/$z1/$z2 -I$dx/$dz -V -T0.25 
gmt grdimage map.grd -R$x1/$x2/$z1/$z2 -JP$zs -C"$colort"  -B5/10WEsN -P -K -X3 -Y$zinc >! "$output"

# Draw core
#psxy $inputc -JP$zs -R$x1/$x2/$z1/$z2 -W5/255/255/255  -P -K -O >> $output

#psscale -C$colort -L -D2.5/-2/5.0/0.4h -B30g15:"": -O -P >> $output
gmt psscale -C"$colort" -L -D4/-2/9.0/0.4h -O -P -K >> "$output"

gmt pstext -R0/20/0/28 -Jx1. -X-8 -Y-21.5 -O -P <<END >> "${output}"
 12 20 16 0.0 1 2 Temperature (K)
END

ps2pdf "$output" "$output2"

